import { expect, test } from "bun:test";
import { decodeFrame, decodePackedSnapshot, engine, encodePackedSnapshot, PackedSnapshotView } from "../src/index.ts";

function settings(order = ["b", "a"]) { return { schemaVersion: 1 as const, id: "packed", worldSize: { x: 100, y: 100 }, entities: order.map(id => ({ id, capabilities: ["movement.state", "transform.state", "custom.state"], "transform.state": { schemaVersion: 1, position: { x: id === "a" ? 10 : 20, y: 30 }, rotation: 0 }, "movement.state": { schemaVersion: 1, velocity: { x: 1, y: 2 }, angularVelocity: 0, enabled: true }, "custom.state": { label: id, value: 4 } })), structures: [], effects: [], counters: [] }; }
test("packed snapshots use explicit type IDs, fixed layouts, and deterministic ordering", () => { const a = encodePackedSnapshot(settings()); const b = encodePackedSnapshot(settings(["a", "b"])); expect(Array.from(a)).toEqual(Array.from(b)); const frame = decodeFrame(a); expect(frame.frameType).toBe(2); expect(frame.schemaVersion).toBe(2); expect(new TextDecoder().decode(frame.payload)).not.toContain("transform.state"); expect(frame.payload.byteLength).toBeLessThan(JSON.stringify(settings()).length); });
test("packed snapshot views read fixed fields without reconstructing settings", () => { const bytes = encodePackedSnapshot(settings()); const decoded = decodePackedSnapshot(bytes); const entity = decoded.view.getEntity("a")!; const transform = entity.getComponent("transform.state")!; expect(transform.x).toBe(10); expect(transform.y).toBe(30); expect(decoded.view.getEntity("b")?.getComponent("movement.state")?.toSettings()).toEqual({ schemaVersion: 1, velocity: { x: 1, y: 2 }, angularVelocity: 0, enabled: true }); expect(decoded.settings.entities[0].capabilities).toEqual(["custom.state", "movement.state", "transform.state"]); expect(decoded.settings.entities[1].capabilities).toEqual(["custom.state", "movement.state", "transform.state"]); expect(decoded.settings.entities.map(entity => entity["transform.state"])).toEqual(settings(["a", "b"]).entities.map(entity => entity["transform.state"])); });
test("writable packed views mutate the received ArrayBuffer without a field copy", () => { const bytes = encodePackedSnapshot(settings(["a"])); const decoded = decodePackedSnapshot(bytes); const transform = decoded.view.getEntity("a")!.getComponent("transform.state")!; transform.x = 55; expect(transform.x).toBe(55); expect(decoded.view.toSettings().entities[0]["transform.state"].position.x).toBe(55); });
test("packed restore uses the existing runtime settings lifecycle", () => { const registry = engine.createSystemRegistry(); registry.register({ id: "noop" }, () => {}); const original = engine.createWorld({ id: "packed", worldSize: { x: 100, y: 100 } }).addEntity(engine.createEntity(settings(["a"]).entities[0]!)).useFramework(registry.select(["noop"])).buildRuntime(registry); const bytes = original.snapshotBinary({ format: "packed" }); const restored = original.constructor.restoreBinary(bytes, registry); expect(restored.snapshot()).toEqual(original.snapshot()); });
test("packed malformed offsets and truncation fail safely", () => { const bytes = encodePackedSnapshot(settings()); expect(() => new PackedSnapshotView(decodeFrame(bytes).payload.subarray(0, 30))).toThrow(); const corrupted = bytes.slice(); new DataView(corrupted.buffer).setUint32(28, 0xfffffff0, true); expect(() => decodePackedSnapshot(corrupted)).toThrow(); });
test("debug names do not change packed bytes", () => { const first = settings(["a"]); const second = structuredClone(first); (second.entities[0] as any)["debug-name"] = "different"; expect(Array.from(encodePackedSnapshot(first))).not.toEqual(Array.from(encodePackedSnapshot(second))); delete (second.entities[0] as any)["debug-name"]; expect(Array.from(encodePackedSnapshot(first))).toEqual(Array.from(encodePackedSnapshot(second))); });
