import type { EngineMovementState, EngineTransformState } from "./entityState.js";
import type { EngineWorldSettings } from "./worldBuilder.js";
import type { JsonValue } from "../contracts/systemSettings.js";
import { createBinaryView as createGenericBinaryView } from "./schema.js";
import type { BinarySchema, BinarySchemaRegistry, RegisteredBinarySchema, BinaryView } from "./schema.js";

export const ROAST_BINARY_PROTOCOL_VERSION = 1;
export const ROAST_BINARY_SCHEMA_VERSION = 1;
export const ROAST_PACKED_SCHEMA_VERSION = 2;
export const ROAST_BINARY_FRAME_TYPE = 1;
export const ROAST_PACKED_FRAME_TYPE = 2;
const MAGIC = 0x54534f52; // ROST, little-endian
const PACKED_MAGIC = 0x314b5052; // RPK1, little-endian
const HEADER_BYTES = 16;
const PACKED_HEADER_BYTES = 44;
const ENTITY_RECORD_BYTES = 20;
const COMPONENT_RECORD_BYTES = 20;
const COMPONENT_TRANSFORM = 1;
const COMPONENT_MOVEMENT = 2;
const COMPONENT_FALLBACK = 0xffff;
const COMPONENT_MODE_FIXED = 1;
const COMPONENT_MODE_REGISTERED = 2;
const COMPONENT_MODE_FALLBACK = 3;
const COMPONENT_REGISTERED = 0xfffe;
const KNOWN_COMPONENT_NAMES = new Map([[COMPONENT_TRANSFORM, "transform.state"], [COMPONENT_MOVEMENT, "movement.state"]]);
function componentName(typeId: number, name: string): string { return KNOWN_COMPONENT_NAMES.get(typeId) ?? name; }
function capabilityRef(name: string, stringId: (value: string) => number): number { if (name === "transform.state") return 0x80000000 | COMPONENT_TRANSFORM; if (name === "movement.state") return 0x80000000 | COMPONENT_MOVEMENT; return stringId(name); }
function capabilityName(ref: number, strings: string[]): string { if ((ref & 0x80000000) !== 0) return KNOWN_COMPONENT_NAMES.get(ref & 0x7fffffff) ?? "unknown.component"; const name = strings[ref]; if (name === undefined) throw new Error("Invalid capability string reference"); return name; }

export interface BinaryStorage { allocate(bytes: Uint8Array): Uint8Array; }
export interface BinarySchemaIdentity { namespace: string; typeId: number; version: number; }
export interface PackedComponentBinding { [componentName: string]: BinarySchemaIdentity; }
export interface PackedTypedSection { key: string; path: string[]; schema: BinarySchemaIdentity; value: unknown; }
export interface PackedSnapshotOptions { registry?: BinarySchemaRegistry; components?: PackedComponentBinding; sections?: PackedTypedSection[]; diagnostics?: boolean; }
export interface PackedSchemaDiagnostic { identity: string; name?: string; count: number; payloadBytes: number; recordBytes: number; }
export interface PackedDiagnostics { frameBytes: number; outerFrameHeaderBytes: number; outerHeaderBytes: number; packedHeaderBytes: number; entityTableBytes: number; componentRecordBytes: number; stringTableBytes: number; tableBytes: number; metadataRegionBytes: number; dataRegionBytes: number; typedSectionDescriptorBytes: number; builtInBytes: number; builtInPackedPayloadBytes: number; registeredComponentBytes: number; registeredComponentPayloadBytes: number; typedSectionBytes: number; typedSectionPayloadBytes: number; fallbackBytes: number; fallbackJsonBytes: number; fallbackPercentage: number; fallbackCount: number; namespaceTableBytes: number; registeredEnvelopeOverheadBytes: number; unattributedBytes: number; physical: { outerFrameHeaderBytes: number; packedHeaderBytes: number; entityTableBytes: number; componentTableBytes: number; stringTableBytes: number; metadataRegionBytes: number; dataRegionBytes: number; unattributedBytes: number }; logical: { fallbackJsonBytes: number; builtInPackedPayloadBytes: number; registeredComponentPayloadBytes: number; typedSectionPayloadBytes: number; registeredEnvelopeOverheadBytes: number; typedSectionDescriptorBytes: number }; schemas: PackedSchemaDiagnostic[]; sections: { key: string; path: string[]; identity: string; payloadBytes: number; overheadBytes: number }[]; }
export interface PackedSnapshotDiagnosticsResult { bytes: Uint8Array; diagnostics: PackedDiagnostics; }
export const arrayBufferStorage: BinaryStorage = { allocate(bytes) { return bytes.slice(); } };
/** BumpArena headers remain allocator metadata and are never part of Roast bytes. */
export function createArenaStorage(arena: { alloc(bytes: Uint8Array): unknown; read(location: unknown): Uint8Array | null }): BinaryStorage {
  return { allocate(bytes) { const location = arena.alloc(bytes); const view = arena.read(location); if (!view) throw new Error("BumpArena allocation could not be read"); return view; } };
}

export const f32 = (): BinarySchema<number> => ({ size: 4, encode: (view, offset, value) => view.setFloat32(offset, value, true), decode: (view, offset) => view.getFloat32(offset, true) });
export const f64 = (): BinarySchema<number> => ({ size: 8, encode: (view, offset, value) => view.setFloat64(offset, value, true), decode: (view, offset) => view.getFloat64(offset, true) });
export const u8 = (): BinarySchema<number> => ({ size: 1, encode: (view, offset, value) => view.setUint8(offset, value), decode: (view, offset) => view.getUint8(offset) });
export const bool = (): BinarySchema<boolean> => ({ size: 1, encode: (view, offset, value) => view.setUint8(offset, value ? 1 : 0), decode: (view, offset) => { const result = view.getUint8(offset); if (result > 1) throw new Error("Invalid boolean value"); return result !== 0; } });
export function struct<T extends Record<string, unknown>>(fields: { [K in keyof T]: BinarySchema<T[K]> }): BinarySchema<T> { const entries = Object.entries(fields) as [keyof T, BinarySchema<T[keyof T]>][], size = entries.reduce((total, [, schema]) => total + schema.size, 0); return { size, encode(view, offset, value) { let cursor = offset; for (const [key, schema] of entries) { schema.encode(view, cursor, value[key]); cursor += schema.size; } }, decode(view, offset) { let cursor = offset; const result = {} as T; for (const [key, schema] of entries) { result[key] = schema.decode(view, cursor); cursor += schema.size; } return result; } }; }
export const transformBinarySchema = struct<{ x: number; y: number; rotation: number }>({ x: f32(), y: f32(), rotation: f32() });
export const movementBinarySchema = struct<{ velocityX: number; velocityY: number; angularVelocity: number; enabled: boolean }>({ velocityX: f32(), velocityY: f32(), angularVelocity: f32(), enabled: bool() });
export function encodeSchema<T>(value: T, schema: BinarySchema<T>, storage: BinaryStorage = arrayBufferStorage): Uint8Array { const bytes = new Uint8Array(schema.size); schema.encode(new DataView(bytes.buffer), 0, value); return storage.allocate(bytes); }
export function decodeSchema<T>(bytes: Uint8Array, schema: BinarySchema<T>): T { if (bytes.byteLength < schema.size) throw new Error("Binary schema payload is truncated"); return schema.decode(new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength), 0); }

function encodeFrameWithSchema(payload: Uint8Array, frameType: number, schemaVersion: number): Uint8Array { const bytes = new Uint8Array(HEADER_BYTES + payload.byteLength); const view = new DataView(bytes.buffer); view.setUint32(0, MAGIC, true); view.setUint16(4, ROAST_BINARY_PROTOCOL_VERSION, true); view.setUint16(6, schemaVersion, true); view.setUint8(8, frameType); view.setUint32(10, payload.byteLength, true); view.setUint16(14, 0, true); bytes.set(payload, HEADER_BYTES); return bytes; }
export function encodeFrame(payload: Uint8Array, frameType = ROAST_BINARY_FRAME_TYPE): Uint8Array { return encodeFrameWithSchema(payload, frameType, ROAST_BINARY_SCHEMA_VERSION); }
export function decodeFrame(bytes: Uint8Array): { protocolVersion: number; schemaVersion: number; frameType: number; payload: Uint8Array } { if (bytes.byteLength < HEADER_BYTES) throw new Error("Binary frame is truncated"); const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength); if (view.getUint32(0, true) !== MAGIC) throw new Error("Invalid Roast binary magic"); const protocolVersion = view.getUint16(4, true), schemaVersion = view.getUint16(6, true), frameType = view.getUint8(8), length = view.getUint32(10, true); if (protocolVersion !== ROAST_BINARY_PROTOCOL_VERSION) throw new Error(`Unsupported Roast binary protocol version ${protocolVersion}`); if (schemaVersion !== ROAST_BINARY_SCHEMA_VERSION && schemaVersion !== ROAST_PACKED_SCHEMA_VERSION) throw new Error(`Unsupported Roast binary schema version ${schemaVersion}`); if (length !== bytes.byteLength - HEADER_BYTES) throw new Error("Invalid binary frame payload length"); return { protocolVersion, schemaVersion, frameType, payload: bytes.subarray(HEADER_BYTES) }; }

function canonicalJson(value: JsonValue): string { if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; if (value !== null && typeof value === "object") return `{${Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonicalJson(item)}`).join(",")}}`; return JSON.stringify(value); }
function jsonBytes(value: JsonValue): Uint8Array<ArrayBuffer> { return new TextEncoder().encode(canonicalJson(value)) as Uint8Array<ArrayBuffer>; }
export function encodeSettings(settings: JsonValue): Uint8Array { return encodeFrame(jsonBytes(settings)); }
export function decodeSettings(bytes: Uint8Array): JsonValue { const frame = decodeFrame(bytes); if (frame.frameType !== ROAST_BINARY_FRAME_TYPE || frame.schemaVersion !== ROAST_BINARY_SCHEMA_VERSION) throw new Error("Not a JSON-backed Roast binary frame"); try { return JSON.parse(new TextDecoder().decode(frame.payload)) as JsonValue; } catch { throw new Error("Invalid Roast binary JSON payload"); } }

function checkedRange(view: DataView, offset: number, length: number, label: string): void { if (!Number.isSafeInteger(offset) || !Number.isSafeInteger(length) || offset < 0 || length < 0 || offset + length > view.byteLength) throw new Error(`Invalid ${label} range`); }
function text(value: string): Uint8Array<ArrayBuffer> { return new TextEncoder().encode(value) as Uint8Array<ArrayBuffer>; }
function readText(bytes: Uint8Array): string { return new TextDecoder().decode(bytes); }
function byteSlice(data: DataView, offset: number, length: number): Uint8Array { checkedRange(data, offset, length, "byte slice"); return new Uint8Array(data.buffer, data.byteOffset + offset, length); }
function concat(chunks: Uint8Array[]): Uint8Array { const result = new Uint8Array(chunks.reduce((n, chunk) => n + chunk.byteLength, 0)); let offset = 0; for (const chunk of chunks) { result.set(chunk, offset); offset += chunk.byteLength; } return result; }
function isRecord(value: unknown): value is Record<string, any> { return typeof value === "object" && value !== null && !Array.isArray(value); }

interface PackedEntity { id: string; capabilities: string[]; components: { name: string; typeId: number; schemaVersion: number; mode: number; bytes: Uint8Array }[]; }
function schemaEncode<T>(schema: BinarySchema<T>, value: T): Uint8Array { if (schema.encodeBytes) return schema.encodeBytes(value); const bytes = new Uint8Array(schema.size); schema.encode(new DataView(bytes.buffer), 0, value); return bytes; }
function schemaDecode<T>(schema: BinarySchema<T>, bytes: Uint8Array): T { if (schema.decodeBytes) return schema.decodeBytes(bytes); return schema.decode(new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength), 0); }
function identityKey(identity: BinarySchemaIdentity): string { return `${identity.namespace}:${identity.typeId}@${identity.version}`; }
function registeredEnvelope(identity: BinarySchemaIdentity, namespaceRef: number, payload: Uint8Array): Uint8Array { const out = new Uint8Array(12 + payload.length); const v = new DataView(out.buffer); v.setUint32(0, namespaceRef, true); v.setUint16(4, identity.typeId, true); v.setUint16(6, identity.version, true); v.setUint32(8, payload.length, true); out.set(payload, 12); return out; }
function readRegisteredEnvelope(bytes: Uint8Array) { if (bytes.length < 12) throw new Error("Registered payload is truncated"); const v = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength), length = v.getUint32(8, true); if (length !== bytes.length - 12) throw new Error("Invalid registered payload length"); return { namespaceRef: v.getUint32(0, true), typeId: v.getUint16(4, true), version: v.getUint16(6, true), payload: bytes.subarray(12) }; }
function componentBytes(name: string, value: unknown, options: PackedSnapshotOptions): { typeId: number; schemaVersion: number; mode: number; bytes: Uint8Array; identity?: BinarySchemaIdentity } { const identity = options.components?.[name]; if (identity) { if (!options.registry) throw new Error(`Registry required for ${name}`); const entry = options.registry.get(identity.namespace, identity.typeId, identity.version); if (!entry) throw new Error(`Missing binary schema ${identity.namespace}:${identity.typeId}@${identity.version}`); return { typeId: COMPONENT_REGISTERED, schemaVersion: identity.version, mode: COMPONENT_MODE_REGISTERED, identity, bytes: schemaEncode(entry.schema, value) }; } if (name === "transform.state" && isRecord(value) && isRecord(value.position)) return { typeId: COMPONENT_TRANSFORM, schemaVersion: 1, mode: COMPONENT_MODE_FIXED, bytes: encodeSchema({ x: value.position.x, y: value.position.y, rotation: value.rotation }, transformBinarySchema) }; if (name === "movement.state" && isRecord(value) && isRecord(value.velocity)) return { typeId: COMPONENT_MOVEMENT, schemaVersion: 1, mode: COMPONENT_MODE_FIXED, bytes: encodeSchema({ velocityX: value.velocity.x, velocityY: value.velocity.y, angularVelocity: value.angularVelocity, enabled: value.enabled }, movementBinarySchema) }; return { typeId: COMPONENT_FALLBACK, schemaVersion: 1, mode: COMPONENT_MODE_FALLBACK, bytes: jsonBytes(value as JsonValue) }; }
function decodeComponent(name: string, typeId: number, mode: number, bytes: Uint8Array, strings: string[], registry?: BinarySchemaRegistry): unknown { if (mode === COMPONENT_MODE_REGISTERED) { if (!registry) throw new Error("Missing binary schema registry"); const envelope = readRegisteredEnvelope(bytes), namespace = strings[envelope.namespaceRef]; if (!namespace) throw new Error("Invalid registered namespace reference"); const entry = registry.get(namespace, envelope.typeId, envelope.version); if (!entry) throw new Error(`Missing binary schema ${namespace}:${envelope.typeId}@${envelope.version}`); return schemaDecode(entry.schema, envelope.payload); } if (mode === COMPONENT_MODE_FIXED && typeId === COMPONENT_TRANSFORM && name === "transform.state") { const value = decodeSchema(bytes, transformBinarySchema); return { schemaVersion: 1, position: { x: value.x, y: value.y }, rotation: value.rotation }; } if (mode === COMPONENT_MODE_FIXED && typeId === COMPONENT_MOVEMENT && name === "movement.state") { const value = decodeSchema(bytes, movementBinarySchema); return { schemaVersion: 1, velocity: { x: value.velocityX, y: value.velocityY }, angularVelocity: value.angularVelocity, enabled: value.enabled }; } if (mode !== COMPONENT_MODE_FALLBACK) throw new Error(`Unsupported packed component ${typeId}`); try { return JSON.parse(readText(bytes)); } catch { throw new Error("Malformed packed fallback component"); } }

export function encodePackedSnapshot(settings: EngineWorldSettings, storageOrOptions: BinaryStorage | PackedSnapshotOptions = arrayBufferStorage, maybeOptions?: PackedSnapshotOptions): Uint8Array {
  const storage = "allocate" in storageOrOptions ? storageOrOptions : arrayBufferStorage; const options = "allocate" in storageOrOptions ? (maybeOptions ?? {}) : storageOrOptions;
  const root = structuredClone({ ...settings, entities: undefined }) as any; delete root.entities;
  const sections = [...(options.sections ?? [])].sort((a, b) => a.key.localeCompare(b.key)); const claimed = sections.map(section => section.path); for (let i = 0; i < claimed.length; i++) for (let j = i + 1; j < claimed.length; j++) { const a = claimed[i]!, b = claimed[j]!; if (a.length === b.length && a.every((v, n) => v === b[n])) throw new Error(`Duplicate typed section path ${sections[i]!.key}`); if (a.every((v, n) => v === b[n])) throw new Error(`Overlapping typed section paths ${sections[i]!.key}/${sections[j]!.key}`); } for (const section of sections) { if (!section.path.length) throw new Error("Typed section path cannot be empty"); let cursor = root; for (let i = 0; i < section.path.length - 1; i++) { if (!isRecord(cursor[section.path[i]!])) throw new Error(`Invalid typed section parent ${section.key}`); cursor = cursor[section.path[i]!]; } delete cursor[section.path[section.path.length - 1]!]; }
  const sourceEntities = (settings.entities as Record<string, any>[]).map(entity => { const components = Object.keys(entity).filter(key => key !== "id" && key !== "capabilities").sort().map(name => ({ name, ...componentBytes(name, entity[name], options) })); return { id: String(entity.id), capabilities: [...(entity.capabilities ?? [])].map(String).sort(), components }; }).sort((a, b) => a.id.localeCompare(b.id));
  const strings: string[] = []; const stringIds = new Map<string, number>(); const stringId = (value: string) => { let id = stringIds.get(value); if (id === undefined) { id = strings.length; strings.push(value); stringIds.set(value, id); } return id; };
  for (const entity of sourceEntities) { stringId(entity.id); for (const capability of entity.capabilities) if (capability !== "transform.state" && capability !== "movement.state") stringId(capability); for (const component of entity.components) { if (component.mode === COMPONENT_MODE_FALLBACK || component.mode === COMPONENT_MODE_REGISTERED) stringId(component.name); if (component.identity) stringId(component.identity.namespace); } }
  const sectionValues: any[] = []; for (const section of sections) { if (!options.registry) throw new Error("Registry required for typed sections"); const entry = options.registry.get(section.schema.namespace, section.schema.typeId, section.schema.version); if (!entry) throw new Error(`Missing binary schema ${section.schema.namespace}:${section.schema.typeId}@${section.schema.version}`); sectionValues.push({ section, payload: registeredEnvelope(section.schema, stringId(section.schema.namespace), schemaEncode(entry.schema, section.value)) }); }
  const componentRecords: { nameIndex: number; typeId: number; schemaVersion: number; mode: number; bytes: Uint8Array; offset: number }[] = []; const entityRecords: { idIndex: number; capabilities: number[]; componentStart: number; componentCount: number; capOffset: number }[] = []; const dataChunks: Uint8Array[] = []; let dataLength = 0;
  const addData = (bytes: Uint8Array) => { const offset = dataLength; dataChunks.push(bytes); dataLength += bytes.byteLength; return offset; };
  for (const entity of sourceEntities) { const capBytes = new Uint8Array(entity.capabilities.length * 4); const capView = new DataView(capBytes.buffer); entity.capabilities.forEach((capability, index) => { const ref = capability === "transform.state" ? (0x80000000 | COMPONENT_TRANSFORM) >>> 0 : capability === "movement.state" ? (0x80000000 | COMPONENT_MOVEMENT) >>> 0 : stringIds.get(capability); if (ref === undefined) throw new Error(`Missing capability string ${capability}`); capView.setUint32(index * 4, ref >>> 0, true); }); const capOffset = addData(capBytes); const componentStart = componentRecords.length; for (const component of entity.components) componentRecords.push({ nameIndex: component.mode === COMPONENT_MODE_FALLBACK || component.mode === COMPONENT_MODE_REGISTERED ? stringId(component.name) : 0, typeId: component.typeId, schemaVersion: component.schemaVersion, mode: component.mode, bytes: component.identity ? registeredEnvelope(component.identity, stringId(component.identity.namespace), component.bytes) : component.bytes, offset: addData(component.identity ? registeredEnvelope(component.identity, stringId(component.identity.namespace), component.bytes) : component.bytes) }); entityRecords.push({ idIndex: stringId(entity.id), capabilities: entity.capabilities.map(capability => capability === "transform.state" ? (0x80000000 | COMPONENT_TRANSFORM) >>> 0 : capability === "movement.state" ? (0x80000000 | COMPONENT_MOVEMENT) >>> 0 : strings.indexOf(capability)), componentStart, componentCount: entity.components.length, capOffset, }); }
  for (const item of sectionValues) { const offset = addData(item.payload); (root.__roastTypedSections ??= []).push({ key: item.section.key, path: item.section.path, namespace: item.section.schema.namespace, typeId: item.section.schema.typeId, version: item.section.schema.version, offset, length: item.payload.length }); }
  const metadata = jsonBytes(root as unknown as JsonValue); const metadataOffset = addData(metadata); const metadataLength = metadata.byteLength; const entityTableOffset = PACKED_HEADER_BYTES; const componentTableOffset = entityTableOffset + entityRecords.length * ENTITY_RECORD_BYTES; const dataOffset = componentTableOffset + componentRecords.length * COMPONENT_RECORD_BYTES; const stringOffset = dataOffset + dataLength; const stringChunks = [new Uint8Array(4)]; new DataView(stringChunks[0]!.buffer).setUint32(0, strings.length, true); for (const value of strings) { const bytes = text(value), header = new Uint8Array(4); new DataView(header.buffer).setUint32(0, bytes.byteLength, true); stringChunks.push(header, bytes); } const stringBytes = concat(stringChunks); const payload = new Uint8Array(stringOffset + stringBytes.byteLength); const view = new DataView(payload.buffer); view.setUint32(0, PACKED_MAGIC, true); view.setUint16(4, 1, true); view.setUint16(6, 0, true); view.setUint32(8, entityRecords.length, true); view.setUint32(12, entityTableOffset, true); view.setUint32(16, componentTableOffset, true); view.setUint32(20, dataOffset, true); view.setUint32(24, dataLength, true); view.setUint32(28, stringOffset, true); view.setUint32(32, stringBytes.byteLength, true); view.setUint32(36, dataOffset + metadataOffset, true); view.setUint32(40, metadataLength, true);
  for (const chunk of dataChunks) payload.set(chunk, dataOffset + dataChunks.slice(0, dataChunks.indexOf(chunk)).reduce((n, item) => n + item.byteLength, 0)); // chunks are unique by construction
  entityRecords.forEach((entity, index) => { const offset = entityTableOffset + index * ENTITY_RECORD_BYTES; view.setUint32(offset, entity.idIndex, true); view.setUint32(offset + 4, dataOffset + entity.capOffset, true); view.setUint16(offset + 8, entity.capabilities.length, true); view.setUint32(offset + 10, entity.componentStart, true); view.setUint16(offset + 14, entity.componentCount, true); view.setUint16(offset + 16, 0, true); view.setUint16(offset + 18, 0, true); });
  componentRecords.forEach((component, index) => { const offset = componentTableOffset + index * COMPONENT_RECORD_BYTES; view.setUint32(offset, component.nameIndex, true); view.setUint16(offset + 4, component.typeId, true); view.setUint16(offset + 6, component.schemaVersion, true); view.setUint8(offset + 8, component.mode); view.setUint8(offset + 9, 0); view.setUint32(offset + 10, dataOffset + component.offset, true); view.setUint32(offset + 14, component.bytes.byteLength, true); view.setUint32(offset + 18, 0, true); }); payload.set(stringBytes as Uint8Array<ArrayBuffer>, stringOffset); return storage.allocate(encodeFrameWithSchema(payload as Uint8Array<ArrayBuffer>, ROAST_PACKED_FRAME_TYPE, ROAST_PACKED_SCHEMA_VERSION));
}

function readStrings(view: DataView, offset: number, length: number): string[] { checkedRange(view, offset, length, "string table"); const end = offset + length; if (length < 4) throw new Error("Truncated packed string table"); const count = view.getUint32(offset, true); let cursor = offset + 4; const result: string[] = []; for (let i = 0; i < count; i += 1) { checkedRange(view, cursor, 4, "string length"); const size = view.getUint32(cursor, true); cursor += 4; checkedRange(view, cursor, size, "string"); result.push(readText(new Uint8Array(view.buffer, view.byteOffset + cursor, size))); cursor += size; } if (cursor !== end) throw new Error("Packed string table has trailing bytes"); return result; }
export function encodePackedSnapshotWithDiagnostics(settings: EngineWorldSettings, options: PackedSnapshotOptions = {}): PackedSnapshotDiagnosticsResult {
  const bytes = encodePackedSnapshot(settings, options); const frame = decodeFrame(bytes); const payload = frame.payload; const view = new DataView(payload.buffer, payload.byteOffset, payload.byteLength);
  const entityCount = view.getUint32(8, true), entityTableBytes = entityCount * ENTITY_RECORD_BYTES; const componentOffset = view.getUint32(16, true), dataOffset = view.getUint32(20, true), dataLength = view.getUint32(24, true), stringOffset = view.getUint32(28, true), stringBytes = view.getUint32(32, true), metadataOffset = view.getUint32(36, true), metadataLength = view.getUint32(40, true); const componentRecordBytes = Math.max(0, dataOffset - componentOffset); const metadata = JSON.parse(readText(byteSlice(view, metadataOffset, metadataLength))) as any; const descriptors = (metadata.__roastTypedSections ?? []) as any[]; const descriptorBytes = descriptors.length ? metadataLength - jsonBytes({ ...metadata, __roastTypedSections: undefined } as JsonValue).byteLength : 0; const schemaMap = new Map<string, PackedSchemaDiagnostic>(); const sectionsDiagnostics: PackedDiagnostics["sections"] = [];
  let registeredComponentBytes = 0, registeredEnvelopeOverheadBytes = 0, fallbackComponentBytes = 0, builtInPackedPayloadBytes = 0, typedSectionPayloadBytes = 0;
  const addSchema = (identity: BinarySchemaIdentity, payloadBytes: number, envelopeBytes: number) => { const key = identityKey(identity); const existing = schemaMap.get(key); const entry = options.registry?.get(identity.namespace, identity.typeId, identity.version); if (existing) { existing.count += 1; existing.payloadBytes += payloadBytes; existing.recordBytes += envelopeBytes; } else schemaMap.set(key, { identity: key, name: entry?.name, count: 1, payloadBytes, recordBytes: envelopeBytes }); };
  const componentCount = view.getUint32(8, true); const componentTableStart = componentOffset + componentCount * ENTITY_RECORD_BYTES;
  const totalComponents = componentRecordBytes / COMPONENT_RECORD_BYTES; for (let i = 0; i < totalComponents; i++) { const at = componentTableStart + i * COMPONENT_RECORD_BYTES; const mode = view.getUint8(at + 8), length = view.getUint32(at + 14, true); if (mode === COMPONENT_MODE_REGISTERED) { const payload = byteSlice(view, view.getUint32(at + 10, true), length), envelope = readRegisteredEnvelope(payload); const namespace = readStrings(view, stringOffset, stringBytes)[envelope.namespaceRef]; if (!namespace) throw new Error("Invalid registered namespace reference"); const identity = { namespace, typeId: envelope.typeId, version: envelope.version }; addSchema(identity, envelope.payload.length, 12); registeredComponentBytes += envelope.payload.length; registeredEnvelopeOverheadBytes += 12; } else if (mode === COMPONENT_MODE_FALLBACK) fallbackComponentBytes += length; else builtInPackedPayloadBytes += length; }
  for (const descriptor of descriptors) { const envelope = readRegisteredEnvelope(byteSlice(view, dataOffset + descriptor.offset, descriptor.length)); const identity = { namespace: descriptor.namespace, typeId: descriptor.typeId, version: descriptor.version }; const payloadBytes = envelope.payload.length; addSchema(identity, payloadBytes, 12); typedSectionPayloadBytes += payloadBytes; registeredEnvelopeOverheadBytes += 12; sectionsDiagnostics.push({ key: descriptor.key, path: descriptor.path, identity: identityKey(identity), payloadBytes, overheadBytes: descriptorBytes }); }
  const fallbackRootBytes = jsonBytes({ ...metadata, __roastTypedSections: undefined } as JsonValue).byteLength; const fallbackJsonBytes = fallbackRootBytes + fallbackComponentBytes; builtInPackedPayloadBytes = Math.max(0, dataLength - registeredComponentBytes - typedSectionPayloadBytes - registeredEnvelopeOverheadBytes - fallbackJsonBytes); const attributed = HEADER_BYTES + PACKED_HEADER_BYTES + entityTableBytes + componentRecordBytes + stringBytes + builtInPackedPayloadBytes + registeredComponentBytes + typedSectionPayloadBytes + registeredEnvelopeOverheadBytes + fallbackJsonBytes; const residualBytes = Math.max(0, bytes.byteLength - attributed); const accountedFallbackBytes = fallbackJsonBytes + residualBytes; const metadataRegionBytes = metadataLength; const dataRegionBytes = dataLength - metadataLength; const physical = { outerFrameHeaderBytes: HEADER_BYTES, packedHeaderBytes: PACKED_HEADER_BYTES, entityTableBytes, componentTableBytes: componentRecordBytes, stringTableBytes: stringBytes, metadataRegionBytes, dataRegionBytes, unattributedBytes: 0 }; const diagnostics: PackedDiagnostics = { frameBytes: bytes.byteLength, outerFrameHeaderBytes: HEADER_BYTES, outerHeaderBytes: HEADER_BYTES, packedHeaderBytes: PACKED_HEADER_BYTES, entityTableBytes, componentRecordBytes, stringTableBytes: stringBytes, tableBytes: stringBytes, metadataRegionBytes, dataRegionBytes, typedSectionDescriptorBytes: descriptorBytes, builtInBytes: builtInPackedPayloadBytes, builtInPackedPayloadBytes, registeredComponentBytes, registeredComponentPayloadBytes: registeredComponentBytes, typedSectionBytes: typedSectionPayloadBytes, typedSectionPayloadBytes, fallbackBytes: accountedFallbackBytes, fallbackJsonBytes, fallbackPercentage: bytes.byteLength ? accountedFallbackBytes / bytes.byteLength * 100 : 0, fallbackCount: (settings.entities as any[]).reduce((n, entity) => n + Object.keys(entity).filter(key => key !== "id" && key !== "capabilities" && !options.components?.[key] && key !== "transform.state" && key !== "movement.state").length, 0), namespaceTableBytes: stringBytes, registeredEnvelopeOverheadBytes, unattributedBytes: 0, physical, logical: { fallbackJsonBytes, builtInPackedPayloadBytes, registeredComponentPayloadBytes: registeredComponentBytes, typedSectionPayloadBytes, registeredEnvelopeOverheadBytes, typedSectionDescriptorBytes: descriptorBytes }, schemas: [...schemaMap.values()], sections: sectionsDiagnostics }; return { bytes, diagnostics }; }
export function decodePackedSnapshot(bytes: Uint8Array, options: { registry?: BinarySchemaRegistry } = {}): { settings: EngineWorldSettings; view: PackedSnapshotView } { const frame = decodeFrame(bytes); if (frame.frameType !== ROAST_PACKED_FRAME_TYPE || frame.schemaVersion !== ROAST_PACKED_SCHEMA_VERSION) throw new Error("Not a packed Roast snapshot"); const view = new PackedSnapshotView(frame.payload, options.registry); return { settings: view.toSettings(), view }; }

export class PackedSnapshotView {
  private readonly bytes: Uint8Array; private readonly data: DataView; private readonly strings: string[]; private readonly entityOffset: number; private readonly componentOffset: number; private readonly entityCount: number; private readonly registry?: BinarySchemaRegistry; private readonly dataOffset: number; private readonly metadataOffset: number; private readonly metadataLength: number;
  public constructor(payload: Uint8Array, registry?: BinarySchemaRegistry) { this.registry = registry; this.bytes = payload; this.data = new DataView(payload.buffer, payload.byteOffset, payload.byteLength); if (payload.byteLength < PACKED_HEADER_BYTES || this.data.getUint32(0, true) !== PACKED_MAGIC || this.data.getUint16(4, true) !== 1) throw new Error("Invalid packed Roast payload"); this.entityCount = this.data.getUint32(8, true); this.entityOffset = this.data.getUint32(12, true); this.componentOffset = this.data.getUint32(16, true); const dataOffset = this.data.getUint32(20, true), dataLength = this.data.getUint32(24, true), stringOffset = this.data.getUint32(28, true), stringLength = this.data.getUint32(32, true), metadataOffset = this.data.getUint32(36, true), metadataLength = this.data.getUint32(40, true); checkedRange(this.data, metadataOffset, metadataLength, "packed metadata"); checkedRange(this.data, this.entityOffset, this.entityCount * ENTITY_RECORD_BYTES, "entity table"); checkedRange(this.data, this.componentOffset, Math.max(0, stringOffset - this.componentOffset), "component table"); checkedRange(this.data, dataOffset, dataLength, "packed data"); this.dataOffset = dataOffset; this.metadataOffset = metadataOffset; this.metadataLength = metadataLength; this.strings = readStrings(this.data, stringOffset, stringLength); }
  public getEntity(id: string): PackedEntityView | undefined { for (let i = 0; i < this.entityCount; i += 1) { const offset = this.entityOffset + i * ENTITY_RECORD_BYTES; if (this.strings[this.data.getUint32(offset, true)] === id) return new PackedEntityView(this.data, this.strings, offset, this.componentOffset, this.registry); } return undefined; }
  public getEntities(): PackedEntityView[] { const result: PackedEntityView[] = []; for (let i = 0; i < this.entityCount; i += 1) result.push(new PackedEntityView(this.data, this.strings, this.entityOffset + i * ENTITY_RECORD_BYTES, this.componentOffset, this.registry)); return result; }
  public getTypedSection(key: string): BinaryView | undefined { const metadata = this.metadataObject(); const descriptor = (metadata.__roastTypedSections as any[] | undefined)?.find(section => section.key === key); if (!descriptor) return undefined; if (!this.registry) throw new Error("Missing binary schema registry"); const entry = this.registry.get(descriptor.namespace, descriptor.typeId, descriptor.version); if (!entry) throw new Error(`Missing binary schema ${descriptor.namespace}:${descriptor.typeId}@${descriptor.version}`); const start = this.dataOffset + descriptor.offset + 12; checkedRange(this.data, start, descriptor.length - 12, "typed section payload"); if (!entry.schema.capabilities?.fixedSize) throw new Error("Typed section schema does not support fixed views"); return createGenericBinaryView(entry.schema, this.bytes, start, false); }
  private metadataObject(): any { checkedRange(this.data, this.metadataOffset, this.metadataLength, "packed metadata"); return JSON.parse(readText(byteSlice(this.data, this.metadataOffset, this.metadataLength))); }
  public toSettings(): EngineWorldSettings { const metadata = this.metadataObject(); const sections = metadata.__roastTypedSections as any[] | undefined; delete metadata.__roastTypedSections; for (const descriptor of sections ?? []) { if (!this.registry) throw new Error("Missing binary schema registry"); const entry = this.registry.get(descriptor.namespace, descriptor.typeId, descriptor.version); if (!entry) throw new Error(`Missing binary schema ${descriptor.namespace}:${descriptor.typeId}@${descriptor.version}`); const start = this.dataOffset + descriptor.offset + 12; checkedRange(this.data, start, descriptor.length - 12, "typed section payload"); const value = schemaDecode(entry.schema, byteSlice(this.data, start, descriptor.length - 12)); let cursor = metadata; for (let i = 0; i < descriptor.path.length - 1; i++) { if (cursor[descriptor.path[i]] !== undefined && !isRecord(cursor[descriptor.path[i]])) throw new Error("Invalid typed section reconstruction parent"); cursor = cursor[descriptor.path[i]] ?? (cursor[descriptor.path[i]] = {}); } cursor[descriptor.path[descriptor.path.length - 1]] = value; } return { ...(metadata as EngineWorldSettings), entities: this.getEntities().map(entity => entity.toSettings()) as JsonValue[] }; }
}
export class PackedEntityView {
  private readonly data: DataView; private readonly bytes: Uint8Array; private readonly strings: string[]; private readonly offset: number; private readonly componentBase: number; private readonly registry?: BinarySchemaRegistry;
  public constructor(data: DataView, strings: string[], offset: number, componentBase: number, registry?: BinarySchemaRegistry) { this.data = data; this.bytes = new Uint8Array(data.buffer, data.byteOffset, data.byteLength); this.strings = strings; this.offset = offset; this.componentBase = componentBase; this.registry = registry; }
  public get id(): string { return this.strings[this.data.getUint32(this.offset, true)]!; }
  public get capabilities(): string[] { const start = this.data.getUint32(this.offset + 10, true), count = this.data.getUint16(this.offset + 14, true); const names: string[] = []; for (let i = 0; i < count; i += 1) { const record = this.componentBase + (start + i) * COMPONENT_RECORD_BYTES; names.push(componentName(this.data.getUint16(record + 4, true), this.strings[this.data.getUint32(record, true)] ?? "")); } return names.sort(); }
  public getComponent(name: string): PackedTransformView | PackedMovementView | undefined { const start = this.data.getUint32(this.offset + 10, true), count = this.data.getUint16(this.offset + 14, true); for (let i = 0; i < count; i += 1) { const record = this.componentBase + (start + i) * COMPONENT_RECORD_BYTES; if (componentName(this.data.getUint16(record + 4, true), this.strings[this.data.getUint32(record, true)] ?? "") !== name) continue; const typeId = this.data.getUint16(record + 4, true), payload = this.data.getUint32(record + 10, true), length = this.data.getUint32(record + 14, true); checkedRange(this.data, payload, length, "component payload"); if (typeId === COMPONENT_TRANSFORM) return new PackedTransformView(this.data, payload, false); if (typeId === COMPONENT_MOVEMENT) return new PackedMovementView(this.data, payload, false); } return undefined; }
  public getRegisteredComponent(name: string, writable = false): BinaryView | undefined { const start = this.data.getUint32(this.offset + 10, true), count = this.data.getUint16(this.offset + 14, true); for (let i = 0; i < count; i++) { const record = this.componentBase + (start + i) * COMPONENT_RECORD_BYTES; const typeId = this.data.getUint16(record + 4, true), mode = this.data.getUint8(record + 8), componentNameValue = this.strings[this.data.getUint32(record, true)] ?? ""; if (mode !== COMPONENT_MODE_REGISTERED || componentNameValue !== name) continue; const payload = this.data.getUint32(record + 10, true), length = this.data.getUint32(record + 14, true); const envelope = readRegisteredEnvelope(byteSlice(this.data, payload, length)); if (!this.registry) throw new Error("Missing binary schema registry"); const namespace = this.strings[envelope.namespaceRef]; if (!namespace) throw new Error("Invalid registered namespace reference"); const entry = this.registry.get(namespace, envelope.typeId, envelope.version); if (!entry) throw new Error(`Missing binary schema ${namespace}:${envelope.typeId}@${envelope.version}`); return createGenericBinaryView(entry.schema, this.bytes, payload + 12, writable); } return undefined; }
  public componentRanges(): { offset: number; length: number }[] { const start = this.data.getUint32(this.offset + 10, true), count = this.data.getUint16(this.offset + 14, true); return Array.from({ length: count }, (_, i) => { const record = this.componentBase + (start + i) * COMPONENT_RECORD_BYTES; return { offset: this.data.getUint32(record + 10, true), length: this.data.getUint32(record + 14, true) }; }); }
  public toSettings(): Record<string, unknown> { const result: Record<string, unknown> = { id: this.id, capabilities: this.capabilities }; const start = this.data.getUint32(this.offset + 10, true), count = this.data.getUint16(this.offset + 14, true); for (let i = 0; i < count; i += 1) { const record = this.componentBase + (start + i) * COMPONENT_RECORD_BYTES; const typeId = this.data.getUint16(record + 4, true), name = componentName(typeId, this.strings[this.data.getUint32(record, true)] ?? ""), mode = this.data.getUint8(record + 8), payload = this.data.getUint32(record + 10, true), length = this.data.getUint32(record + 14, true); checkedRange(this.data, payload, length, "component payload"); result[name] = decodeComponent(name, typeId, mode, byteSlice(this.data, payload, length), this.strings, this.registry); } return result; }
}
export class PackedTransformView { public constructor(private readonly data: DataView, private readonly offset: number, private readonly readOnly = true) {} private set(offset: number, value: number) { if (this.readOnly) throw new Error("Packed view is read-only"); this.data.setFloat32(this.offset + offset, value, true); } public get x() { return this.data.getFloat32(this.offset, true); } public set x(value: number) { this.set(0, value); } public get y() { return this.data.getFloat32(this.offset + 4, true); } public set y(value: number) { this.set(4, value); } public get rotation() { return this.data.getFloat32(this.offset + 8, true); } public set rotation(value: number) { this.set(8, value); } public toSettings(): EngineTransformState { return { schemaVersion: 1, position: { x: this.x, y: this.y }, rotation: this.rotation }; } }
export class PackedMovementView { public constructor(private readonly data: DataView, private readonly offset: number, private readonly readOnly = true) {} public get velocityX() { return this.data.getFloat32(this.offset, true); } public get velocityY() { return this.data.getFloat32(this.offset + 4, true); } public get angularVelocity() { return this.data.getFloat32(this.offset + 8, true); } public get enabled() { return this.data.getUint8(this.offset + 12) !== 0; } public toSettings(): EngineMovementState { return { schemaVersion: 1, velocity: { x: this.velocityX, y: this.velocityY }, angularVelocity: this.angularVelocity, enabled: this.enabled }; } }

export class BinaryBackedTransform { private readonly bytes: Uint8Array; private readonly view: DataView; public constructor(value: EngineTransformState, storage: BinaryStorage = arrayBufferStorage) { this.bytes = encodeSchema({ x: value.position.x, y: value.position.y, rotation: value.rotation }, transformBinarySchema, storage); this.view = new DataView(this.bytes.buffer, this.bytes.byteOffset, this.bytes.byteLength); } public get x() { return this.view.getFloat32(0, true); } public set x(value: number) { this.view.setFloat32(0, value, true); } public get y() { return this.view.getFloat32(4, true); } public set y(value: number) { this.view.setFloat32(4, value, true); } public get rotation() { return this.view.getFloat32(8, true); } public set rotation(value: number) { this.view.setFloat32(8, value, true); } public toSettings(): EngineTransformState { return { schemaVersion: 1, position: { x: this.x, y: this.y }, rotation: this.rotation }; } public toBinary(): Uint8Array { return this.bytes; } }
export function binaryBackedTransform(value: EngineTransformState, storage?: BinaryStorage): BinaryBackedTransform { return new BinaryBackedTransform(value, storage); }
export function binarySnapshot(settings: EngineWorldSettings, storage: BinaryStorage = arrayBufferStorage): Uint8Array { return storage.allocate(encodeSettings(settings as unknown as JsonValue)); }
export function restoreBinarySnapshot(bytes: Uint8Array, options: { registry?: BinarySchemaRegistry } = {}): EngineWorldSettings { const frame = decodeFrame(bytes); if (frame.frameType === ROAST_PACKED_FRAME_TYPE) return decodePackedSnapshot(bytes, options).settings; return decodeSettings(bytes) as unknown as EngineWorldSettings; }
export type BinarySnapshotFormat = "json" | "packed";
export function packedSnapshot(settings: EngineWorldSettings, storage: BinaryStorage = arrayBufferStorage, options?: PackedSnapshotOptions): Uint8Array { return encodePackedSnapshot(settings, storage, options); }
