import { binary, createBinarySchemaRegistry, encodePackedSnapshot, decodePackedSnapshot } from "../src/index.ts";
import { loadPackedSnapshotAsset } from "../src/build.ts";
const player = binary.struct({ hp: binary.u16(), flags: binary.u8() });
const effect = binary.taggedUnion({ tag: binary.u8(), variants: { 1: binary.struct({ x: binary.f32(), y: binary.f32() }), 2: binary.struct({ amount: binary.u16() }) } });
const rule = binary.struct({ turn: binary.u32(), active: binary.u8() });
const registry = createBinarySchemaRegistry().register({ namespace: "example-game", typeId: 1, version: 1, name: "player", schema: player }).register({ namespace: "example-game", typeId: 2, version: 1, name: "effect", schema: binary.array(effect) }).register({ namespace: "example-game", typeId: 3, version: 1, name: "rule", schema: rule });
const settings: any = { schemaVersion: 1, id: "bench", worldSize: { x: 1000, y: 1000 }, entities: Array.from({ length: 100 }, (_, i) => ({ id: `e-${i}`, capabilities: ["transform.state", "movement.state", "example.player"], "transform.state": { schemaVersion: 1, position: { x: i, y: i }, rotation: 0 }, "movement.state": { schemaVersion: 1, velocity: { x: 1, y: 2 }, angularVelocity: 0, enabled: true }, "example.player": { hp: 100 + i, flags: 3 }, effects: [{ tag: 1, value: { x: 1, y: 2 } }] })), structures: [], effects: [], counters: [], ruleState: { turn: 7, active: 1 }, notes: { text: "unregistered" } };
const options: any = { registry, components: { "example.player": { namespace: "example-game", typeId: 1, version: 1 } }, sections: [{ key: "rule", path: ["ruleState"], schema: { namespace: "example-game", typeId: 3, version: 1 }, value: settings.ruleState }] };
for (let i = 0; i < 100; i++) { JSON.stringify(settings); encodePackedSnapshot(settings); encodePackedSnapshot(settings, options); }
const measure = (fn: () => unknown) => { const start = performance.now(); for (let i = 0; i < 500; i++) fn(); return (performance.now() - start) / 500; };
const jsonText = JSON.stringify(settings); const json = new TextEncoder().encode(jsonText).byteLength; const fallback = encodePackedSnapshot(settings); const packed = encodePackedSnapshot(settings, options); const runtimePacked = packed.slice(); for (let i = 0; i < 100; i++) { JSON.parse(jsonText); loadPackedSnapshotAsset(runtimePacked); decodePackedSnapshot(runtimePacked, { registry }); } const runtime = (fn: () => unknown) => measure(fn); const view = decodePackedSnapshot(runtimePacked, { registry }).view; const component = view.getEntity("e-50")!.getRegisteredComponent("example.player")!; const typed = view.getTypedSection("rule")!;
console.log(JSON.stringify({ entities: 100, iterations: 500, jsonBytes: json, fallbackBytes: fallback.byteLength, registryBytes: packed.byteLength, buildTime: { jsonEncodeMs: measure(() => JSON.stringify(settings)), fallbackEncodeMs: measure(() => encodePackedSnapshot(settings)), registryEncodeMs: measure(() => encodePackedSnapshot(settings, options)) }, runtime: { jsonParseMs: runtime(() => JSON.parse(jsonText)), assetLoadMs: runtime(() => loadPackedSnapshotAsset(runtimePacked)), viewConstructionMs: runtime(() => decodePackedSnapshot(runtimePacked, { registry }).view), componentLookupMs: runtime(() => view.getEntity("e-50")!.getRegisteredComponent("example.player")), componentGetterMs: runtime(() => component.get("hp")), typedLookupMs: runtime(() => view.getTypedSection("rule")), typedGetterMs: runtime(() => typed.get("turn")), fullDecodeMs: runtime(() => decodePackedSnapshot(runtimePacked, { registry })) } }, null, 2));
